name: Generate Snake Animation

on:
  schedule:
    # Se ejecuta todos los días a medianoche
    - cron: '0 0 * * *'
  # Esto te permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v2
        id: snake-gif
        with:
          # MUY IMPORTANTE: Asegúrate de que este es tu nombre de usuario de GitHub
          github_user_name: HectorDanielAyarachiFuentes
          
          # Archivos de salida
          svg_out_path: dist/github-contribution-grid-snake.svg
 
      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
